# Andreas Kirsch

SET(SOIL_DIR CACHE PATH "SOIL root directory")

SET(SOIL_LIBRARY_DIR ${SOIL_DIR}/lib)
SET(SOIL_INCLUDE_DIR ${SOIL_DIR}/include)

MARK_AS_ADVANCED(SOIL_LIBRARY_DIR SOIL_INCLUDE_DIR)

FIND_LIBRARY(SOIL_LIBRARY_RELEASE	soil.lib   PATHS ${SOIL_LIBRARY_DIR})
FIND_LIBRARY(SOIL_LIBRARY_DEBUG		soild.lib  PATHS ${SOIL_LIBRARY_DIR})

SET(SOIL_LIBRARY 	debug ${SOIL_LIBRARY_DEBUG}
					optimized ${SOIL_LIBRARY_RELEASE})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SOIL DEFAULT_MSG SOIL_LIBRARY SOIL_INCLUDE_DIR)