# Andreas Kirsch - adapted from FindNiven.cmake

SET(YAMLCPP_DIR CACHE PATH "yaml-cpp root directory")

SET(YAMLCPP_LIBRARY_DIR ${YAMLCPP_DIR}/lib)
SET(YAMLCPP_INCLUDE_DIR ${YAMLCPP_DIR}/include)

MARK_AS_ADVANCED(YAMLCPP_LIBRARY_DIR YAMLCPP_INCLUDE_DIR)

FIND_LIBRARY(YAMLCPP_LIBRARY_RELEASE	libyaml-cppmd.lib   PATHS ${YAMLCPP_LIBRARY_DIR})
FIND_LIBRARY(YAMLCPP_LIBRARY_DEBUG		libyaml-cppmdd.lib   PATHS ${YAMLCPP_LIBRARY_DIR})

SET(YAMLCPP_LIBRARY 	debug ${YAMLCPP_LIBRARY_DEBUG}
						optimized ${YAMLCPP_LIBRARY_RELEASE})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(AntTweakBar DEFAULT_MSG YAMLCPP_LIBRARY YAMLCPP_INCLUDE_DIR)